<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>FSharp.Astro.Fits.UI</AssemblyName>
    <RootNamespace>FSharp.Astro.Fits.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSharp.Astro.Fits\Fits.fsproj" />
  </ItemGroup>

</Project>
