module TypeProviderTests

open System
open System.IO
open System.Net
open Xunit
open FSharp.Astro.Fits
open FSharp.Astro.Fits.Typed
open FSharp.Astro.Units
open Generators

/// Serves one byte array at a local URL until disposed.
let serve (bytes: byte[]) : string * IDisposable =
    let listener = new HttpListener()

    let rec start (tries: int) : int =
        let port = Random.Shared.Next(20000, 60000)
        listener.Prefixes.Clear()
        listener.Prefixes.Add $"http://127.0.0.1:{port}/"

        try
            listener.Start()
            port
        with _ when tries > 0 ->
            start (tries - 1)

    let port = start 10

    let rec respond () = async {
        match! listener.GetContextAsync() |> Async.AwaitTask |> Async.Catch with
        | Choice1Of2 context ->
            context.Response.ContentLength64 <- int64 bytes.Length
            do!
                context.Response.OutputStream.WriteAsync(bytes, 0, bytes.Length)
                |> Async.AwaitTask
            context.Response.Close()
            return! respond ()
        | Choice2Of2 _ -> ()
    }

    Async.Start(respond ())

    $"http://127.0.0.1:{port}/sample.fits",
    {
        new IDisposable with
            member _.Dispose() =
                listener.Stop()
                listener.Close()
    }

[<Literal>]
let Fixtures = __SOURCE_DIRECTORY__ + "/fixtures"

[<Literal>]
let Sample = Fixtures + "/sample.fits"

type Obs = FitsProvider<Sample>

[<Fact>]
let ``keywords are typed properties`` () =
    use file = Obs.Load Sample
    let primary = file.Primary
    Assert.Equal("M31", primary.OBJECT)
    Assert.Equal(30.0, primary.EXPTIME)
    Assert.Equal("V", primary.FILTER)
    Assert.Equal("2026-10-05", primary.DATE_OBS)
    Assert.Equal(0.5, primary.ESO_DET_DIT)
    Assert.Equal(2L, primary.NAXIS)
    Assert.True primary.SIMPLE
    Assert.Equal<string list>([ "generated by fitsharp" ], primary.Comments)
    Assert.Equal(Some "M31", Header.tryString "OBJECT" primary.Header)
    Assert.Equal(0, primary.Info.Index)
    Assert.Equal(3, file.File.Count)

[<Fact>]
let ``images are typed by BITPIX`` () =
    use file = Obs.Load Sample
    Assert.Equal<int[]>([| 2; 3 |], file.Primary.Shape)
    Assert.Equal<float32[]>([| 1.f; 2.f; 3.f; 4.f; 5.f; 6.f |], file.Primary.Data)
    Assert.Equal<int16[]>([| -32768s; -32767s; 32767s; -32761s |], file.SCI.Data)
    Assert.Equal<float[]>([| 0.0; 1.0; 65535.0; 7.0 |], file.SCI.Pixels)
    Assert.Equal(BitPix.Int16, file.SCI.Image.Data.BitPix)

[<Fact>]
let ``tables have typed rows and columns`` () =
    use file = Obs.Load Sample
    let cat = file.CAT
    Assert.Equal(2, cat.Count)
    Assert.Equal<int[]>([| 1; 2 |], cat.ID)
    Assert.Equal<string[]>([| "alpha"; "beta" |], cat.NAME)
    // TUNIT3 is Jy, so the column comes out tagged.
    Assert.Equal<float32<Jy>[]>([| 1.5f<Jy>; 2.5f<Jy> |], cat.FLUX)
    Assert.Equal<float32[][]>([| [| 1.f; 2.f; 3.f |]; [| 4.f |] |], cat.SPEC)
    Assert.Equal<int16[]>([| 1s; 2s; 3s; 4s; 5s; 6s |], cat.FLAGS)
    let row = cat.Rows[1]
    Assert.Equal(1, row.Index)
    Assert.Equal(2, row.ID)
    Assert.Equal("beta", row.NAME)
    Assert.Equal(2.5f<Jy>, row.FLUX)
    Assert.Equal<float32[]>([| 4.f |], row.SPEC)
    Assert.Equal<int16[]>([| 4s; 5s; 6s |], row.FLAGS)
    Assert.Equal(None, row.OK)
    Assert.Equal(Some true, (cat.Row 0).OK)
    Assert.Equal(2, cat.Table.Rows)
    Assert.Equal(Some "CAT", cat.Info.Name)

[<Fact>]
let ``HDUs are found by EXTNAME rather than position`` () =
    use original = Fits.openFile Sample
    let swapped =
        Fits.toBytes [ Fits.copy original 0; Fits.copy original 2; Fits.copy original 1 ]
    use file = Obs.Parse swapped
    Assert.Equal(1, file.SCI.Info.Index)
    Assert.Equal(2, file.CAT.Info.Index)
    Assert.Equal("beta", file.CAT.Rows[1].NAME)

[<Fact>]
let ``a file missing a keyword fails when that keyword is read`` () =
    use original = Fits.openFile Sample

    let stripped = {
        Fits.copy original 0 with
            Header = Header.remove "FILTER" original.Primary.Header
    }

    use file = Obs.Parse(Fits.toBytes [ stripped ])
    Assert.Equal("M31", file.Primary.OBJECT)
    Assert.Throws<Collections.Generic.KeyNotFoundException>(fun () -> file.Primary.FILTER |> ignore)
    |> ignore

[<Fact>]
let ``Load accepts seekable and non-seekable streams`` () =
    use stream = File.OpenRead Sample
    use file = Obs.Load stream
    Assert.Equal("M31", file.Primary.OBJECT)
    use unseekable = new NonSeekableStream(File.ReadAllBytes Sample)
    use buffered = Obs.Load unseekable
    Assert.Equal<int[]>([| 1; 2 |], buffered.CAT.ID)

[<Fact>]
let ``GetSample opens the sample the type came from`` () =
    use file = Obs.GetSample()
    Assert.Equal("M31", file.Primary.OBJECT)
    Assert.Equal(3, file.File.Count)

[<Fact>]
let ``Load and AsyncLoad fetch URLs`` () =
    let url, server = serve (File.ReadAllBytes Sample)
    use server = server
    use file = Obs.AsyncLoad url |> Async.RunSynchronously
    Assert.Equal("M31", file.Primary.OBJECT)
    use again = Obs.Load url
    Assert.Equal("beta", again.CAT.Rows[1].NAME)

[<Fact>]
let ``AsyncLoad opens local paths too`` () =
    use file = Obs.AsyncLoad Sample |> Async.RunSynchronously
    Assert.Equal(0.5, file.Primary.ESO_DET_DIT)

[<Literal>]
let Samples = Sample + ";" + Fixtures + "/sample2.fits"

type Multi = FitsProvider<Samples>

[<Fact>]
let ``several samples make keywords optional and widen types`` () =
    use first = Multi.Load Sample
    Assert.Equal(Some "V", first.Primary.FILTER)
    Assert.Equal(30.0, first.Primary.EXPTIME)
    Assert.Equal(None, first.Primary.GAIN)
    use second = Multi.Load(Fixtures + "/sample2.fits")
    Assert.Equal(None, second.Primary.FILTER)
    Assert.Equal(60.0, second.Primary.EXPTIME)
    Assert.Equal(Some 1.2, second.Primary.GAIN)

type Dump = FitsProvider<"fixtures/headers.txt", ResolutionFolder=__SOURCE_DIRECTORY__>

[<Fact>]
let ``a text header dump is a valid sample`` () =
    use file = Dump.Load Sample
    Assert.Equal("M31", file.Primary.OBJECT)
    Assert.Equal<int[]>([| 1; 2 |], file.CAT.ID)
    Assert.Equal("beta", file.CAT.Rows[1].NAME)

type WithSchema =
    FitsProvider<Sample, Schema="Primary.EXTRA: float option; CAT.ORIGIN: string option, Primary.EXPTIME: int">

[<Fact>]
let ``schema overrides add and retype keywords`` () =
    use file = WithSchema.Load Sample
    Assert.Equal(None, file.Primary.EXTRA)
    Assert.Equal(None, file.CAT.ORIGIN)
    Assert.Throws<Collections.Generic.KeyNotFoundException>(fun () -> file.Primary.EXPTIME |> ignore)
    |> ignore

type LenientObs = FitsProvider<Sample, Lenient=true>

[<Fact>]
let ``lenient providers open non-conforming files`` () =
    use original = Fits.openFile Sample
    let bytes = Fits.toBytes [ Fits.copy original 0 ]
    let unpadded =
        Array.sub bytes 0 (int original.Primary.DataOffset + int original.Primary.DataLength)
    use file = LenientObs.Parse unpadded
    Assert.Equal("M31", file.Primary.OBJECT)
    Assert.Throws<FitsException>(fun () -> Obs.Parse unpadded |> ignore) |> ignore

/// The unit of a flux density per unit wavelength, which TUNIT3 of the units fixture spells in the
/// IAU style as "erg s-1 cm-2 Angstrom-1".
[<Measure>]
type flam = erg / (s cm^2 angstrom)

type Measured = FitsProvider<"fixtures/units.txt", ResolutionFolder=__SOURCE_DIRECTORY__>

/// A file shaped like the units fixture.
let measured =
    Fits.toBytes [
        Fits.primary
            (Header.set "BUNIT" (CardValue.String "Jy") Header.empty)
            (Image.create [| 2; 2 |] (ImageData.Float32 [| 1.f; 2.f; 3.f; 4.f |]))
        Fits.binaryTable (Header.set "EXTNAME" (CardValue.String "UNITS") Header.empty) [
            Table.ofFloat64s "FLUX" [| 1500.0; 2500.0 |] |> Table.withUnit "mJy"
            Table.ofFloat32s "RA" [| 10.f; 20.f |] |> Table.withUnit "deg"
            Table.ofFloat32s "FLAM" [| 1.f; 2.f |]
            |> Table.withUnit "erg s-1 cm-2 Angstrom-1"
            Table.ofFloat32s "SB" [| 3.f; 4.f |] |> Table.withUnit "Jy/beam"
            Table.ofInt32s "NPIX" [| 5; 6 |] |> Table.withUnit "pixel"
        ]
    ]

[<Fact>]
let ``TUNIT gives a floating point column a unit of measure`` () =
    use file = Measured.Parse measured
    let units = file.UNITS
    Assert.Equal<float<mJy>[]>([| 1500.0<mJy>; 2500.0<mJy> |], units.FLUX)
    Assert.Equal<float32<deg>[]>([| 10.f<deg>; 20.f<deg> |], units.RA)
    Assert.Equal<float32<flam>[]>([| 1.f<flam>; 2.f<flam> |], units.FLAM)
    Assert.Equal(20.f<deg>, units.Rows[1].RA)

[<Fact>]
let ``a unit with no measure behind it leaves the column bare`` () =
    use file = Measured.Parse measured
    // Nothing here declares a measure for a beam.
    Assert.Equal<float32[]>([| 3.f; 4.f |], file.UNITS.SB)
    // An integer column keeps its unit in the documentation only.
    Assert.Equal<int[]>([| 5; 6 |], file.UNITS.NPIX)

[<Fact>]
let ``BUNIT gives the physical pixels a unit of measure`` () =
    use file = Measured.Parse measured
    Assert.Equal<float<Jy>[]>([| 1.0<Jy>; 2.0<Jy>; 3.0<Jy>; 4.0<Jy> |], file.Primary.Pixels)
    // Data is what is stored, before BZERO and BSCALE, so it carries no unit.
    Assert.Equal<float32[]>([| 1.f; 2.f; 3.f; 4.f |], file.Primary.Data)

type AsciiCat = FitsProvider<"fixtures/ascii.txt", ResolutionFolder=__SOURCE_DIRECTORY__>

/// A file shaped like the ASCII fixture.
let asciiBytes =
    Fits.toBytes [
        Fits.emptyPrimary Header.empty
        Fits.asciiTable (Header.set "EXTNAME" (CardValue.String "ACAT") Header.empty) [
            Ascii.ofStrings "NAME" 6 [| "alpha"; "beta" |]
            Ascii.ofInt64s "ID" 4 [| 1L; -22L |]
            Ascii.ofFloat64s "RA" 8 3 [| 10.5; 266.417 |] |> Ascii.withUnit "deg"
            Ascii.ofExponentials "FLUX" 11 4 [| 1.5; 2.0 |] |> Ascii.withUnit "mJy"
        ]
    ]

[<Fact>]
let ``an ASCII table gets typed rows and columns`` () =
    use file = AsciiCat.Parse asciiBytes
    let cat = file.ACAT
    Assert.Equal(2, cat.Count)
    Assert.Equal<string[]>([| "alpha"; "beta" |], cat.NAME)
    // An Iw field of any width decodes as int64.
    Assert.Equal<int64[]>([| 1L; -22L |], cat.ID)
    // The real forms decode as float, and TUNIT gives them their measure.
    Assert.Equal<float<deg>[]>([| 10.5<deg>; 266.417<deg> |], cat.RA)
    Assert.Equal<float<mJy>[]>([| 1.5<mJy>; 2.0<mJy> |], cat.FLUX)

[<Fact>]
let ``ASCII rows read one cell at a time`` () =
    use file = AsciiCat.Parse asciiBytes
    let cat = file.ACAT
    let row = cat.Rows[1]
    Assert.Equal(1, row.Index)
    Assert.Equal("beta", row.NAME)
    Assert.Equal(-22L, row.ID)
    Assert.Equal(266.417<deg>, row.RA)
    Assert.Equal(2.0<mJy>, row.FLUX)
    Assert.Equal("alpha", (cat.Row 0).NAME)

[<Fact>]
let ``the untyped ASCII table is reachable from the provided type`` () =
    use file = AsciiCat.Parse asciiBytes
    let table = file.ACAT.Table
    Assert.Equal(2, table.Rows)
    Assert.Equal(32, table.RowLength)
    Assert.Equal<int[]>([| 1; 8; 13; 22 |], table.Columns |> Array.map (fun c -> c.Start))
    Assert.Equal(HduKind.AsciiTable, file.ACAT.Info.Kind)
